# Generated by Django 4.1.4 on 2022-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nifty_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BANKNIFTY', models.CharField(max_length=150)),
                ('DATE', models.DateField(blank=True)),
                ('TIME', models.CharField(max_length=50)),
                ('OPEN', models.CharField(max_length=150)),
                ('HIGH', models.CharField(max_length=150)),
                ('LOW', models.CharField(max_length=150)),
                ('CLOSE', models.CharField(max_length=150)),
                ('VOLUME', models.CharField(max_length=150)),
            ],
        ),
    ]
